### ISSUE TITLE
Mais opções de tempo para enquetes

### ISSUE THREAD

**Issue by StarryAster** [IsabelaY/mastodon#10]
### Ideia

Adicionar algumas possibilidades de tempo para pesquisas. Prioridade:

- 3 horas, 12 horas
- 2 semanas, 1 mês
- 15 minutos, 2 horas, 2 dias

### Motivo

Os tempos na lista de tempos são muito espaçados:

1. 5 minutos
2. 30 minutos (6 vezes o anterior)
3. 1 hora (2 vezes o anterior)
4. 6 horas (6 vezes o anterior)
5. 1 dia (4 vezes o anterior)
6. 3 dias (3 vezes o anterior)
7. 7 dias (~2,3 vezes o anterior)

Acho que ter sempre 2-3 vezes o tempo da opção anterior é mais ideal.

Também acho que enquetes de mais tempo podem ser úteis. Por exemplo, ao organizar algo com antecedência, talvez uma enquete de duas semanas ou um mês possa ser mais ideal do que uma de uma semana; uma pessoa pode lembrar de compartilhá-la bastante e/ou fixá-la no perfil para ela ter visibilidade durante esse tempo todo.

Para enquetes mais pessoais sobre o perfil, como algo fixado do tipo "você está no meu perfil por conta de qual tipo de postagem?" ou "qual desses pronomes você prefere usar pra mim?", enquetes mais longas (1 mês, 2 meses, 3 meses, 6 meses) podem ser legais (mesmo que tecnicamente dê pra usar enquetes de uma semana).

**Comment by eurritz** [comment]
Acho que opções mais padronizadas, de duas a três vezes a cada tempo da opção anterior, são uma boa alternativa.
