### ISSUE TITLE
Aumento de caracteres em determinados campos

### ISSUE THREAD

**Issue by StarryAster** [IsabelaY/mastodon#111]
Mastodon aumentou o limite de descrições de imagem para 1500 para ser três vezes maior do que um toot, assim como Twitter deixa ter uma descrição maior do que um Tweet, se eu não me engano.

Então, acho que nosso limite de descrições de imagem deveria ser aumentado de 1500 para 2400 (tamanho de brilho), 3000 (número mais redondo) ou 5000 (um pouco mais do que o dobro de um brilho).

Não sei se é o mesmo limite para descrições de áudio e vídeo, pode ser bom conferir e deixar eles iguais.

Notas administrativas também requerem 500 caracteres como tamanho máximo, ainda que precisemos de mais coisas para adicionar mais links ou descrições do que houve. Eu não acho que alguém da administração vai trollar e colar um script do Bee Movie, então não vejo motivo para qualquer limite, mas se for pra ter um, que seja 4000 ou outro número grande.

Eu não sei se esse limite é só para notas em usuáries (na interface de moderação) ou se também é o mesmo pro comentário interno de instâncias e tal, pode ser bom checar (já que não há porque limitar o comentário interno relacionado a instâncias).

Tentei ver se o limite de nota pra usuáries (no aplicativo web) é ruim, mas parece ser relativamente longo, então acho que pode ficar como está...?

**Comment by StarryAster** [comment]
Ah, também percebi que o número máximo de caracteres para denúncia é 1000. Acho que ao menos 2000 (ou 2400 pra combinar com brilho/3000 pra ser maior do que brilho) seria melhor. Só tem que ver como ficaria em servidor remoto, se a denúncia sairia cortada ou daria erro.

**Comment by IsabelaY** [comment]
Aumentei o limite de caracteres das notas de moderação pra 4000 e dos reports para 2000, o limite das descrições de imagem eu não alterei porque acho que outros servidores iriam cortar se passasse do limite de lá.
