### ISSUE TITLE
Compatibilidade com markdown/HTML vindo de outras instâncias

### ISSUE THREAD

**Issue by StarryAster** [IsabelaY/mastodon#4]
### Ideia

Aceitar rich text de outras instâncias e deixar desativar / ativar cada elemento assim como acontece no BBCode

### Motivo

BBCode deve ser usado por uma minoria de instâncias em relação a markdown, a esse ponto.

### Problema

Estamos em uma fase de transição meio estranha no Mastodon, aonde glitch-soc acabou de ativar markdown e mastomain planeja implementar de forma diferente.

Pode ser uma boa ideia ver como essas coisas se desenvolvem antes de tentar conseguir compatibilidade.

https://github.com/tootsuite/mastodon/pull/10787
https://github.com/glitch-soc/mastodon/pull/994
https://mastodon.social/@Gargron/102125096955948360

**Comment by IsabelaY** [comment]
Implementado com o merge com o Hometown.
