### ISSUE TITLE
Caixa de aviso de conteúdo aberta por padrão

### ISSUE THREAD

**Issue by StarryAster** [IsabelaY/mastodon#6]
### Ideia

Deixar a caixa de composição de toots assim por padrão:

![image](https://user-images.githubusercontent.com/43053987/58061604-385fa000-7b4d-11e9-869f-8449743f8617.png)
[Caixa de composição de toots com CW marcado e caixa de aviso de conteúdo aberta]

### Motivo

Usar aviso de conteúdo para deixar pessoas escolherem se querem engajar ou não com diversos assuntos é algo essencial para a cultura do canto do fediverso mais queer em geral, e também para as regras da instância.

Acredito que algo assim lembra melhor usuáries de considerarem colocar um aviso/assunto antes de postar, e ajuda usuáries noves que nunca tiveram contato com o conceito a colocar avisos.

Como é possível postar algo com aviso de conteúdo aberto sem colocar nada no aviso (e assim a postagem fica sem aviso), isso também economiza tempo/esforço de pessoas que frequentemente usam ACs.

### Coisas a serem consideradas

Acho boa ideia ter opção para desativar a caixa aberta por padrão nas preferências.

Também pode ser interessante mudar o texto placeholder para "Aviso de conteúdo (opcional)", para que noves usuáries entendam que não precisam sempre usar ACs só por ter aquela caixa aberta.

Isso talvez dê um pouco mais de trabalho, mas ao invés de deixar o botão de AC clicável para trocar entre aparecer/não aparecer a caixa mesmo quando ela aparece por padrão, dá pra só deixar o botão aparecendo se a pessoa tiver colocado nas preferências pra não mostrar a caixa de AC por padrão.

**Comment by IsabelaY** [comment]
Feito.
